# Module Imports

In [22]:
## IMPORT MODULES
import pandas as pd
import numpy as np
from sklearn import linear_model
from scipy.interpolate import griddata
import scipy.odr


In [23]:
## IMPORT PLOTTING MODULES
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d
import matplotlib as mpl
from matplotlib import cm
%matplotlib widget

# Dataframe

In [24]:
## FULL DATAFRAME
df_raw = pd.read_csv("WS_2-Policy_Summary.csv")

## DROP EXTRANEOUS DATAPOINTS
# df_raw = df_raw.drop(df_raw[(df_raw['landing_rate']<=0.15) & (df_raw['vz_d']>=2.5)].index)
# df_raw = df_raw.drop(df_raw[(df_raw['landing_rate']<=0.15) & (df_raw['vx_d']>=1.0)].index)
# df_raw = df_raw.dropna()
df_raw = df_raw.drop(df_raw[df_raw['My_d']<-7.7].index)




## GROUP RAW DATA BY IC AND FILTER BY MAX LANDING RATE
df_raw_max = df_raw.groupby(['vz_d','vx_d']).agg({'landing_rate':"max"}).reset_index()
idx = df_raw.groupby(['vz_d','vx_d'])['landing_rate'].transform(max) == df_raw['landing_rate']
df_max = df_raw[idx].reset_index()


## CLEAN RAW DATA
df_max['My_d'] = df_max['My_d'].apply(lambda x: np.abs(x)) # Convert My to magnitude
df_max['My_d'] = df_max['My_d'].apply(lambda x: 7.7 if x>7.7 else x) # Cap My_d to max possible moment




In [26]:
# TEMPLATE FOR LINEAR REGRESSION
from sklearn.linear_model import LinearRegression

def linreg(X ,Y):
    # perform multivariate or univariate
    # X = [var1 var2]
    # y = var3
    reg = LinearRegression(normalize=True)
    reg.fit(X,Y)

    intercept = reg.intercept_ 
    coef = reg.coef_
    
    R2 = reg.score(X,Y) # built in function for r^2
    
    ypred = reg.predict(X) # plot x vs. ypred for line or plane
    
    return ypred,intercept,coef,R2


# Landing Rate Data

In [27]:
## LANDING RATE DATA (RAW)
fig = plt.figure()
ax = fig.add_subplot(111,projection="3d")

# DEFINE VARIABLES
X = df_max['vx_d']
Y = df_max['vz_d']
Z = df_max['landing_rate']


# CREATE PLOTS AND COLOR BAR
ax.scatter(X,Y,Z)


# PLOT LIMITS AND INFO
ax.set_zlim(0,1)

ax.set_xlabel('X-Velocity (m/s)')
ax.set_ylabel('Z-Velocity (m/s)')
ax.set_zlabel('Landing Rate (%)')
ax.set_title('Optimal Policy Landing Rate')

plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [28]:
## AVG LANDING RATE SURFACE
fig = plt.figure()
ax = fig.add_subplot(111,projection="3d")

# DEFINE VARIABLES
X = df_max['vx_d']
Y = df_max['vz_d']
Z = df_max['landing_rate']

# DEFINE COLOR FORMATS AND LIMITS
cmap = mpl.cm.jet
norm = mpl.colors.Normalize(vmin=0,vmax=1)

# CREATE PLOTS AND COLOR BAR
ax.plot_trisurf(X,Y,Z,cmap = cmap,norm=norm,edgecolors='grey',linewidth=0.25)
fig.colorbar(mpl.cm.ScalarMappable(norm=norm, cmap=cmap),label="Landing Rate (%)")


# PLOT LIMITS AND INFO
ax.set_zlim(0,1)

ax.set_xlabel('X-Velocity (m/s)')
ax.set_ylabel('Z-Velocity (m/s)')
ax.set_zlabel('Landing Rate (%)')
ax.set_title('Landing Rate (Raw Data)')


plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

ValueError: x and y arrays must have a length of at least 3

In [15]:
df_temp = df_max.query(f"vx_d<={0.0} & vz_d<={2.5}")
df_temp

index  vz_d  vx_d  trial_num  landing_rate  RREV_threshold    G1    G2  \
30    313  2.25   0.0          0      0.566667            4.50  7.13  5.59   
44    409  2.50   0.0          2      0.500000            4.28  5.86  3.82   

    RREV_sig  G1_sig  G2_sig  RREV_trigger      OF_y      My_d  \
30      0.13    0.04    0.07      4.856765  0.001706  7.157882   
44      0.05    0.09    0.01      4.595667  0.001733  5.825067   

             impact_eul        impact_tdelta alpha_mu alpha_sigma  \
30  -36.362742807358394  0.20023529411764518  [0. 0.]     [0. 0.]   
44   -157.1441296858511  0.24346666666664685  [0. 0.]     [0. 0.]   

              mu_ini   sigma_ini  
30  [1.74 6.38 5.85]  [2. 2. 2.]  
44  [6.92 5.37 4.31]  [2. 2. 2.]

In [29]:
## AVG LANDING RATE SMOOTHED SURFACE
fig = plt.figure()
ax = fig.add_subplot(111,projection="3d")

# DEFINE VARIABLES
X = df_max['vx_d']
Y = df_max['vz_d']
Z = df_max['landing_rate']

# SOMETHING ABOUT DEFINING A GRID
xi = np.linspace(X.min(),X.max(),(len(Z)//3))
yi = np.linspace(Y.min(),Y.max(),(len(Z)//3))
zi = griddata((X, Y), Z, (xi[None,:], yi[:,None]), method='linear')
xig, yig = np.meshgrid(xi, yi)

# DEFINE COLOR FORMAT AND LIMITS
cmap = mpl.cm.jet
norm = mpl.colors.Normalize(vmin=0,vmax=1)

# CREATE PLOTS AND COLOR BAR
surf = ax.plot_surface(xig, yig, zi,cmap=cmap,norm=norm,edgecolors='grey',linewidth=0.25)
# surf = ax.plot_surface(xig, yig, zi,cmap=cmap,norm=norm)
# surf = ax.contour(xig, yig, zi,cmap=cmap,norm=norm)

fig.colorbar(mpl.cm.ScalarMappable(norm=norm, cmap=cmap),label="Landing Rate (%)")

# PLOT LIMITS AND INFO
ax.set_zlim(0,1)

ax.set_xlabel('X-Velocity (m/s)')
ax.set_ylabel('Z-Velocity (m/s)')
ax.set_zlabel('Landing Rate (%)')
ax.set_title('Landing Rate (Raw Data)')


plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

ValueError: No points given

# RREV vs IC

In [17]:
fig = plt.figure()
ax = fig.add_subplot(111,projection="3d")

# CLEAN DATA
df_temp = df_max.query(f"landing_rate>={0.4}")




# LINEAR REGRESSION
X_reg = df_temp[['vx_d','vz_d']]
Y_reg = df_temp['RREV_threshold']

ypred, intercept,coef,R2 = linreg(X_reg,Y_reg)
print(f"Equation: RREV_reg = {intercept:.2f} + {coef[0]:.2f}*vx_d + {coef[1]:.2f}*vz_d \n")
print(f"R^2 = {R2:.3f}")


# DEFINE VARIABLES
X = df_temp['vx_d']
Y = df_temp['vz_d']
Z = df_temp['RREV_threshold']
C = df_temp['RREV_threshold']


# CREATE PLOTS AND COLOR BAR
cmap = mpl.cm.rainbow
norm = mpl.colors.Normalize(vmin=3.5,vmax=5.5)
ax.scatter(X,Y,Z,c=C,cmap=cmap,norm=norm,zorder=1)
ax.plot_trisurf(X,Y,ypred,alpha=0.5,label='Linear_Regression',zorder=2)
fig.colorbar(mpl.cm.ScalarMappable(norm=norm, cmap=cmap),label="RREV_threshold (1/s)")



# PLOT LIMITS AND INFO
ax.set_xlim(0,2.75)
ax.set_ylim(1.0,4.5)
ax.set_zlim(3,6)

ax.set_xlabel('X-Velocity (m/s)')
ax.set_ylabel('Z-Velocity (m/s)')
ax.set_zlabel('RREV_threshold (1/s)')
ax.set_title('RREV_thr vs IC - (Optimal Data)')

plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Equation: RREV_reg = 5.51 + 0.00*vx_d + -0.35*vz_d 

R^2 = 0.590


In [18]:
fig = plt.figure()
ax = fig.add_subplot(111,projection="3d")

# CLEAN DATA
df_temp = df_max.query(f"landing_rate>={0.4}")


# DEFINE VARIABLES
X = df_temp['vx_d']
Y = df_temp['vz_d']
Z = df_temp['RREV_threshold']

# SOMETHING ABOUT DEFINING A GRID
xi = np.linspace(X.min(),X.max(),(len(Z)//10))
yi = np.linspace(Y.min(),Y.max(),(len(Z)//10))
zi = griddata((X, Y), Z, (xi[None,:], yi[:,None]), method='linear')
xig, yig = np.meshgrid(xi, yi)

# DEFINE COLOR FORMAT AND LIMITS
cmap = mpl.cm.jet
norm = mpl.colors.Normalize(vmin=3.5,vmax=5.5)

# CREATE PLOTS AND COLOR BAR
surf = ax.plot_surface(xig, yig, zi,cmap=cmap,norm=norm,edgecolors='grey',linewidth=0.25)
fig.colorbar(mpl.cm.ScalarMappable(norm=norm, cmap=cmap),label="RREV_threshold")

# PLOT LIMITS AND INFO
ax.set_xlim(0,2.75)
ax.set_ylim(1.0,4.5)
ax.set_zlim(3,6)

ax.set_xlabel('X-Velocity (m/s)')
ax.set_ylabel('Z-Velocity (m/s)')
ax.set_zlabel('RREV_threshold (1/s)')

ax.set_title('Optimal RREV_thr vs IC')
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

# Rotation Time Data

In [19]:
fig = plt.figure()
ax = fig.add_subplot(111,projection="3d")

# CLEAN DATA
df_temp = df_max.query(f"landing_rate>={0.4}")

# DEFINE VARIABLES
X = df_temp['RREV_threshold']
Y = df_temp['OF_y']
Z = df_temp['impact_tdelta']
C = df_temp['landing_rate']


# CREATE PLOTS AND COLOR BAR
ax.scatter(X,Y,Z)

cmap = mpl.cm.rainbow
norm = mpl.colors.Normalize(vmin=0,vmax=1)
ax.scatter(X,Y,Z,c=C,cmap=cmap,norm=norm)
fig.colorbar(mpl.cm.ScalarMappable(norm=norm, cmap=cmap),label="Landing Rate %)")



# PLOT LIMITS AND INFO
ax.set_xlabel('RREV (1/s)')
ax.set_ylabel('OF_y (rad/s)')
ax.set_zlabel('Delta_t (s)')

ax.set_title('Time Rotating vs IC (Optimal Data)')

ax.set_zlim(0,0.5)




plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

# My_d vs IC Data

In [20]:
fig = plt.figure()
ax = fig.add_subplot(111,projection="3d")

# CLEAN DATA
df_temp = df_max.query(f"landing_rate>={0.4}")

# DEFINE VARIABLES
X = df_temp['vx_d']
Y = df_temp['vz_d']
Z = df_temp['My_d']
C = df_temp['landing_rate']


# CREATE PLOTS AND COLOR BAR
ax.scatter(X,Y,Z)

cmap = mpl.cm.rainbow
norm = mpl.colors.Normalize(vmin=0,vmax=1)
ax.scatter(X,Y,Z,c=C,cmap=cmap,norm=norm)
fig.colorbar(mpl.cm.ScalarMappable(norm=norm, cmap=cmap),label="Landing Rate %)")



# PLOT LIMITS AND INFO
ax.set_xlabel('X-Velocity (m/s)')
ax.set_ylabel('Z-Velocity (m/s)')
ax.set_zlabel('My_d (N*mm)')

ax.set_title('My_d vs IC (Optimal Data)')

ax.set_zlim(0,10)




plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

# Impact Angle Data

In [21]:
fig = plt.figure()
ax = fig.add_subplot(111,projection="3d")

# CLEAN DATA
df_temp = df_max.query(f"landing_rate>={0.4}")


# DEFINE VARIABLES
X = df_temp['vx_d']
Y = df_temp['vz_d']
Z = -df_temp['impact_eul']
C = df_temp['landing_rate']


# CREATE PLOTS AND COLOR BAR
cmap = mpl.cm.rainbow
norm = mpl.colors.Normalize(vmin=0,vmax=1)
ax.scatter(X,Y,Z,c=C,cmap=cmap,norm=norm)
fig.colorbar(mpl.cm.ScalarMappable(norm=norm, cmap=cmap),label="Landing Rate")



# PLOT LIMITS AND INFO
ax.set_xlabel('X-Velocity (m/s)')
ax.set_ylabel('Z-Velocity (m/s)')
ax.set_zlabel('Impact Angle (deg)')

ax.set_title('Impact Angle vs IC (Optimal Data)')

ax.set_zlim(60,180)
ax.set_zticks([60,90,120,150,180,210])



plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

TypeError: bad operand type for unary -: 'str'

In [14]:
fig = plt.figure()
ax = fig.add_subplot(111,projection="3d")

# CLEAN DATA
df_temp = df_max.query(f"landing_rate>={0.4}")


# DEFINE VARIABLES
X = df_temp['vx_d']
Y = df_temp['vz_d']
Z = -df_temp['impact_eul']
C = df_temp['landing_rate']


# CREATE PLOTS AND COLOR BAR
cmap = mpl.cm.rainbow
norm = mpl.colors.Normalize(vmin=60,vmax=180)
ax.plot_trisurf(X,Y,Z,cmap=cmap,norm=norm)
fig.colorbar(mpl.cm.ScalarMappable(norm=norm, cmap=cmap),label="Landing Rate",orientation="horizontal")



# PLOT LIMITS AND INFO
ax.set_xlabel('X-Velocity (m/s)')
ax.set_ylabel('Z-Velocity (m/s)')
ax.set_zlabel('Impact Angle (deg)')

ax.set_title('Impact Angle vs IC (Optimal Data)')

ax.set_zlim(60,180)
ax.set_zticks([60,90,120,150,180,210])



plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [15]:
## AVG LANDING RATE SMOOTHED SURFACE
fig = plt.figure()
ax = fig.add_subplot(111,projection="3d")

# CLEAN DATA
df_temp = df_max.query(f"landing_rate>={0.4}")

# DEFINE VARIABLES
X = df_temp['vx_d']
Y = df_temp['vz_d']
Z = -df_temp['impact_eul']

# SOMETHING ABOUT DEFINING A GRID
xi = np.linspace(X.min(),X.max(),(len(Z)//10))
yi = np.linspace(Y.min(),Y.max(),(len(Z)//10))
zi = griddata((X, Y), Z, (xi[None,:], yi[:,None]), method='linear')
xig, yig = np.meshgrid(xi, yi)

# DEFINE COLOR FORMAT AND LIMITS
cmap = mpl.cm.rainbow
norm = mpl.colors.Normalize(vmin=60,vmax=180)

# CREATE PLOTS AND COLOR BAR
surf = ax.plot_surface(xig, yig, zi,cmap=cmap,norm=norm,edgecolors='grey',linewidth=0.25)
# surf = ax.plot_surface(xig, yig, zi,cmap=cmap,norm=norm)
# surf = ax.contour(xig, yig, zi,cmap=cmap,norm=norm)

fig.colorbar(mpl.cm.ScalarMappable(norm=norm, cmap=cmap),label="Impact Angle (deg)")

# PLOT LIMITS AND INFO
ax.set_xlabel('X-Velocity (m/s)')
ax.set_ylabel('Z-Velocity (m/s)')
ax.set_zlabel('Impact Angle (deg)')

ax.set_title('Impact Angle vs IC (Optimal Data)')

ax.set_zlim(60,180)
ax.set_zticks([60,90,120,150,180,210])


plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

# Moment vs RREV

In [16]:
fig = plt.figure()
ax = fig.add_subplot(111)

# CLEAN DATA
df_temp = df_max.query(f"landing_rate>={0.4}")

# DEFINE VARIABLES
X = df_temp['RREV_threshold']
Y = df_temp['My_d']
C = df_temp['landing_rate']


# CREATE PLOTS AND COLOR BAR
cmap = mpl.cm.Greys
norm = mpl.colors.Normalize(vmin=0,vmax=1)
ax.scatter(X,Y,c=C,cmap=cmap,norm=norm)
fig.colorbar(mpl.cm.ScalarMappable(norm=norm, cmap=cmap),label="Landing Rate (%)")



# PLOT LIMITS AND INFO
ax.set_xlabel('RREV_threshold (1/s)')
ax.set_ylabel('My_d (N*mm)')
ax.set_title('Policy: My_d vs RREV_thr')


ax.grid()
ax.set_xlim(2,7)
ax.set_ylim(0,10)
ax.hlines(7.77,2,7)
ax.text(2.05,8.1,'Motors Maxed Out \n(My_d = 7.7 N*mm)')




plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [17]:
fig = plt.figure()
ax = fig.add_subplot(111)

# CLEAN DATA
df_temp = df_max.query(f"landing_rate>={0.4}")

# DEFINE VARIABLES
X = df_temp['RREV_threshold']
Y = df_temp['My_d']
C = df_temp['vz_d']

# CREATE PLOTS AND COLOR BAR
cmap = mpl.cm.rainbow
norm = mpl.colors.Normalize(vmin=1.5,vmax=4)
ax.scatter(X,Y,c=C,cmap=cmap,norm=norm)
fig.colorbar(mpl.cm.ScalarMappable(norm=norm, cmap=cmap),label="Z-Velocity (m/s)")



# PLOT LIMITS AND INFO
ax.set_xlabel('RREV_threshold (1/s)')
ax.set_ylabel('My_d (N*mm)')
ax.set_title('Policy: My_d vs RREV_thr')




ax.grid()
ax.set_xlim(2,7)
ax.set_ylim(0,10)
ax.hlines(7.77,2,7)
ax.text(2.05,8.1,'Motors Maxed Out \n(My_d = 7.7 N*mm)')




plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

# POLICY FITTING

## RAW POLICY RELATION

In [18]:
fig = plt.figure()
ax = fig.add_subplot(111,projection="3d")

# CLEAN DATA
df_temp = df_max.query(f"landing_rate>={0.6}")



# DEFINE VARIABLES
X = df_temp['RREV_threshold']
Y = df_temp['OF_y']
Z = df_temp['My_d']
C = df_temp['landing_rate']


# CREATE PLOTS AND COLOR BAR
cmap = mpl.cm.rainbow
norm = mpl.colors.Normalize(vmin=0,vmax=1)
ax.scatter(X,Y,Z,c=C,cmap=cmap,norm=norm)
fig.colorbar(mpl.cm.ScalarMappable(norm=norm, cmap=cmap),label="Landing Rate")



# PLOT LIMITS AND INFO
ax.set_xlim(6,2)
ax.set_ylim(-10,0)
ax.set_zlim(0,10)

ax.set_xlabel('RREV (1/s)')
ax.set_ylabel('OF_y (rad/s)')
ax.set_zlabel('My_d (N*mm)')

ax.set_title('Raw Policy Relation')



plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

# LINEAR MODEL FIT

## Regression with y-based loss

In [19]:
fig = plt.figure()
ax = fig.add_subplot(111,projection="3d")

# CLEAN DATA
df_reg = df_max.query(f"landing_rate>={0.6}")


# LINEAR REGRESSION
X_reg = df_reg[['RREV_threshold','OF_y']]
Y_reg = df_reg['My_d']

ypred, intercept,coef,R2 = linreg(X_reg,Y_reg)
print(f"Equation: My_d = {intercept:.2f} + {coef[0]:.2f}*RREV + {coef[1]:.2f}*OF_y \n")
print(f"R^2 = {R2:.3f}")



# DEFINE VARIABLES
X = df_reg['RREV_threshold']
Y = df_reg['OF_y']
Z = df_reg['My_d']
C = df_reg['landing_rate']


# CREATE PLOTS AND COLOR BAR
cmap = mpl.cm.rainbow
norm = mpl.colors.Normalize(vmin=0,vmax=1)
ax.plot_trisurf(X_reg['RREV_threshold'],X_reg['OF_y'],ypred,alpha=0.75,label='Linear_Regression',zorder=1) # Surface plot
ax.scatter(X,Y,Z,c=C,cmap=cmap,norm=norm) # Scatter plot
fig.colorbar(mpl.cm.ScalarMappable(norm=norm, cmap=cmap),label="Landing Rate")



# PLOT LIMITS AND INFO
ax.set_xlim(6,2)
ax.set_ylim(-10,0)
ax.set_zlim(0,10)

ax.set_xlabel('RREV (1/s)')
ax.set_ylabel('OF_y (rad/s)')
ax.set_zlabel('My_d (N*mm)')

ax.set_title('Optimal Policy Relation \n(Z-Based Error)')



plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Equation: My_d = -5.21 + 2.32*RREV + 0.40*OF_y 

R^2 = 0.173


In [24]:
df_cov = df_reg[['RREV_threshold','OF_y','My_d']]
df_cov.cov()

RREV_threshold      OF_y      My_d
RREV_threshold        0.128934 -0.366187  0.153750
OF_y                 -0.366187  3.202645  0.418622
My_d                  0.153750  0.418622  3.016097

In [20]:
df_reg.query(f"My_d<={3.5}").sort_values('OF_y')

index  vz_d  vx_d  trial_num  landing_rate  RREV_threshold     G1    G2  \
6       87  1.50  2.25          3      0.964286            5.04   3.09  1.66   
29     308  2.00  2.75          3      1.000000            4.84   2.28  2.42   
15     178  1.75  2.00          5      1.000000            4.75   8.38  1.96   
27     293  2.00  2.25          3      0.956522            4.79   7.16  3.17   
56     494  2.50  2.75          5      0.933333            4.87   9.44  4.15   
14     169  1.75  1.75          3      0.958333            4.95   6.27  2.00   
39     379  2.25  2.25          0      0.866667            4.94   4.68  0.50   
4       75  1.50  1.75          3      0.875000            4.86   3.32  1.60   
3       64  1.50  1.50          0      0.600000            5.35   2.56  1.49   
26     283  2.00  2.00          3      1.000000            4.54   2.26  4.90   
38     377  2.25  2.00          5      0.920000            4.75   6.32  1.88   
93     657  3.25  2.75          0      0.900000            4.57   5.61  0.97   
13     167  1.75  1.50          5      0.793103            4.92   2.27  3.66   
24     270  2.00  1.50          5      0.846154            5.04   4.58  1.04   
92     654  3.25  2.50          1      1.000000            4.16   6.26  3.17   
79     615  3.00  2.25          4      0.923077            4.38   4.48  0.72   
51     457  2.50  1.75          1      0.800000            4.70   4.55  1.78   
105    704  3.50  2.75          0      1.000000            3.94   5.10  1.99   
12     155  1.75  1.25          2      0.642857            5.25   1.94  1.47   
67     565  2.75  2.00          5      1.000000            4.18   8.55  5.92   
23     262  2.00  1.25          4      0.640000            5.34   6.07  4.42   
117    751  3.75  2.75          0      1.000000            4.05   9.87  6.03   
91     651  3.25  2.25          3      0.814815            4.22   7.21  4.67   
50     450  2.50  1.50          3      0.750000            4.64   4.22  2.24   
129    802  4.00  2.75          2      0.900000            3.95   6.26  4.08   
116    747  3.75  2.50          1      1.000000            3.90   7.89  4.51   
90     645  3.25  2.00          2      0.954545            4.07   5.98  2.48   
128    800  4.00  2.50          3      0.965517            4.04   7.75  2.20   
66     551  2.75  1.75          2      0.862069            4.32   3.46  2.79   
77     605  3.00  1.75          3      0.642857            4.41   8.21  2.36   
115    743  3.75  2.25          0      0.800000            4.08   5.42  2.07   
22     245  2.00  1.00          0      0.666667            4.81   6.83  3.04   
127    797  4.00  2.25          3      0.766667            4.21   9.35  4.79   
114    741  3.75  2.00          4      0.862069            3.99   7.60  4.15   
126    791  4.00  2.00          0      0.833333            3.98   8.44  3.10   
101    687  3.50  1.75          0      0.640000            4.01   4.53  4.10   
124    782  4.00  1.50          1      0.800000            4.15   8.34  2.67   
111    727  3.75  1.25          2      0.620690            3.99   7.24  0.58   
121    768  4.00  0.75          1      0.633333            4.21   8.56  5.58   
108    719  3.75  0.50          3      0.666667            3.90   7.53  3.62   
94     660  3.50  0.00          2      0.800000            4.43  12.41  1.85   

     RREV_sig  G1_sig  G2_sig  RREV_trigger      OF_y      My_d  impact_eul  \
6        0.00    0.03    0.04      5.700370 -6.846444  3.089370  -79.882310   
29       0.02    0.09    0.00      5.231533 -6.063600  2.301367  -92.828947   
15       0.09    1.50    0.46      5.603286 -5.736214  3.404357  -91.498347   
27       0.06    0.10    0.25      5.497864 -5.611909  2.168455  -90.439828   
56       0.02    0.52    0.14      5.339429 -5.429357  2.949464 -105.826224   
14       0.01    0.03    0.13      5.816348 -5.210217  2.618348  -80.102154   
39       0.02    0.11    0.11      5.548846 -5.084692  2.315192  -84.448864   
4        0.0

## Regression with x-based loss


In [21]:
fig = plt.figure()
ax = fig.add_subplot(111,projection="3d")

# CLEAN DATA
df_reg = df_max.query(f"landing_rate>={0.6}")


# LINEAR REGRESSION
X_reg = df_reg[['My_d','OF_y']]
Y_reg = df_reg['RREV_threshold']

ypred, intercept,coef,R2 = linreg(X_reg,Y_reg)
print(f"Equation: RREV_thr = {intercept:.2f} + {coef[0]:.2f}*My_d + {coef[1]:.2f}*OF_y \n")
# print(f"Equation: My_d = ((RREV_thr - {intercept:.2f}) - {coef[1]:.2f}*OF_y)/{coef[0]:.2f})")
print(f"R^2 = {R2:.3f}")



# DEFINE VARIABLES
X = df_reg['My_d']
Y = df_reg['OF_y']
Z = df_reg['RREV_threshold']
C = df_reg['landing_rate']


# CREATE PLOTS AND COLOR BAR
cmap = mpl.cm.rainbow
norm = mpl.colors.Normalize(vmin=0,vmax=1)
ax.plot_trisurf(X_reg['My_d'],X_reg['OF_y'],ypred,alpha=0.75,label='Linear_Regression',zorder=1) # Surface plot
ax.scatter(X,Y,Z,c=C,cmap=cmap,norm=norm) # Scatter plot
fig.colorbar(mpl.cm.ScalarMappable(norm=norm, cmap=cmap),label="Landing Rate (%)")



# PLOT LIMITS AND INFO
ax.set_xlim(10,0)
ax.set_ylim(0,-10)
ax.set_zlim(3,6)



ax.set_xlabel('My_d (N*mm)')
ax.set_ylabel('OF_y (rad/s)')
ax.set_zlabel('RREV (1/s)')

ax.set_title('Optimal Policy Relation \n(X-Based Error)')



plt.show()




Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Equation: RREV_thr = 3.88 + 0.07*My_d + -0.12*OF_y 

R^2 = 0.431


# Regression w/ Orthogonal Distance

In [22]:
fig = plt.figure()
ax = fig.add_subplot(111,projection="3d")

# CLEAN DATA
df_reg = df_max.query(f"landing_rate>={0.6}")


# LINEAR REGRESSION
def linfit(beta, x):
    return beta[0]*x[0] + beta[1]*x[1] + beta[2] 

x1 = df_reg['RREV_threshold']
x2 = df_reg['OF_y']
y = df_reg['My_d']
x = np.row_stack( (x1, x2) ) #odr doesn't seem to work with column_stack

linmod = scipy.odr.Model(linfit)
data = scipy.odr.Data(x, y)
odrfit = scipy.odr.ODR(data, linmod, beta0=[1., 1., 1.])
odrres = odrfit.run()
odrres.pprint()


y_reg = odrres.beta[0]*x1 + odrres.beta[1]*x2 + odrres.beta[2]

print(f"Equation: My_d = {odrres.beta[2]:.2f} + {odrres.beta[0]:.2f}*RREV + {odrres.beta[1]:.2f}*OF_y \n")
# print(f"R^2 = {R2:.3f}")



# DEFINE VARIABLES
X = df_max['RREV_threshold']
Y = df_max['OF_y']
Z = df_max['My_d']
C = df_max['landing_rate']


# CREATE PLOTS AND COLOR BAR
cmap = mpl.cm.rainbow
norm = mpl.colors.Normalize(vmin=0,vmax=1)
ax.plot_trisurf(x1,x2,y_reg,alpha=0.75,label='Linear_Regression',zorder=1) # Surface plot
ax.scatter(X,Y,Z,c=C,cmap=cmap,norm=norm) # Scatter plot
fig.colorbar(mpl.cm.ScalarMappable(norm=norm, cmap=cmap),label="Landing Rate (%)")



# PLOT LIMITS AND INFO
ax.set_xlim(6,2)
ax.set_ylim(-10,0)
ax.set_zlim(0,10)

ax.set_xlabel('RREV (1/s)')
ax.set_ylabel('OF_y (rad/s)')
ax.set_zlabel('My_d (N*mm)')

ax.set_title('Optimal Policy Relation \n(Orthogonal Regression)')



plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Beta: [ 14.24775773   1.80019726 -54.95025462]
Beta Std Error: [ 3.3874206   0.45801538 14.15137079]
Beta Covariance: [[ 156.13758091   18.29283331 -651.16969919]
 [  18.29283331    2.8544952   -74.05045078]
 [-651.16969919  -74.05045078 2724.99819251]]
Residual Variance: 0.07349043227476758
Inverse Condition #: 0.004802836564341187
Reason(s) for Halting:
  Sum of squares convergence
Equation: My_d = -54.95 + 14.25*RREV + 1.80*OF_y 



In [23]:
import numpy as np
import scipy.odr

n = 1000
t = np.linspace(0, 1, n)

def linfit(beta, x):
    return beta[0]*x[0] + beta[1]*x[1] + beta[2] #notice changed indices for x

x1 = 2.5*np.sin(2*np.pi*6*t)+4
x2 = 0.5*np.sin(2*np.pi*7*t + np.pi/3)+2

x = np.row_stack( (x1, x2) ) #odr doesn't seem to work with column_stack

e = 0.25*np.random.randn(n)
y = 3*x[0] + 4*x[1] + 5 + e #indices changed

linmod = scipy.odr.Model(linfit)
data = scipy.odr.Data(x, y)
odrfit = scipy.odr.ODR(data, linmod, beta0=[1., 1., 1.])
odrres = odrfit.run()
odrres.pprint()


Beta: [3.00757658 4.0363251  4.89358429]
Beta Std Error: [0.00442904 0.02225373 0.04857541]
Beta Covariance: [[ 8.43859074e-03  7.28986530e-05 -3.39001941e-02]
 [ 7.28986530e-05  2.13037410e-01 -4.26458700e-01]
 [-3.39001941e-02 -4.26458700e-01  1.01504036e+00]]
Residual Variance: 0.002324607792610536
Inverse Condition #: 0.03035728824479211
Reason(s) for Halting:
  Sum of squares convergence


In [25]:
odrres.beta

array([3.00757658, 4.0363251 , 4.89358429])

In [26]:
fig = plt.figure()
ax = fig.add_subplot(111,projection="3d")
y_reg = odrres.beta[0]*x1 + odrres.beta[1]*x2 + odrres.beta[2]

ax.scatter(x1,x2,y)
ax.plot_trisurf(x1,x2,y_reg)


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …